### PR TITLE
Add data attributes for terra-functional-testing

### PR DESCRIPTION
**Pull request by mjhenkes**
### Summary

Adding new data attributes to support terra-functional-testing

Per: https://github.com/cerner/terra-toolkit/pull/464#discussion_r523026053

Closes #

### Deployment Link

https://terra-dev-site-deployed-pr-#.herokuapp.com/

### Additional Details

Thank you for contributing to Terra.
@cerner/terra

### CODE REVIEW

**Review by StephenEsser — APPROVED** [review]

**Review by emilyrohrbough — APPROVED** [review]

**Review by yuderekyu — APPROVED** [review]
are we planning on documenting this?

**Comment by mjhenkes** [comment]
@yuderekyu, I think the documentation for the data attributes themselves would live with terra-functional-testing

> By default terra-functional-testing package expects content to be marked with the `data-terra-test-content` attribute..... 

If we added documentation here it would be along the lines of stating compatibly with the terra-functional-testing package, which I think is expected? Additionally this change will be invisible, the new attributes won't affect anything in the current terra-toolkit tests and since we now have the new data attributes, terra-functional tests should run fine too on this version of terra-dev-site and above.

**Comment by benbcai** [comment]
> @yuderekyu, I think the documentation for the data attributes themselves would live with terra-functional-testing
> 
> > By default terra-functional-testing package expects content to be marked with the `data-terra-test-content` attribute.....
> 
> If we added documentation here it would be along the lines of stating compatibly with the terra-functional-testing package, which I think is expected? Additionally this change will be invisible, the new attributes won't affect anything in the current terra-toolkit tests and since we now have the new data attributes, terra-functional tests should run fine too on this version of terra-dev-site and above.

I got here a bit late but here is the doc I added in terra-functional-testing: https://github.com/cerner/terra-toolkit/pull/464/files#diff-67d5712e4a79202db1118cf318f95c62b2a9c82940a5e6f511315e77384d1552

**Comment by benbcai** [comment]
+1 on the PR.

**Pull request merged**
